repos:
  - repo: https://github.com/ReliutionKaran/pre-commitcheck.git
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-xml
      - id: check-xml-xpath
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
