repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest release tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2  # Use the latest release tag
    hooks:
      - id: flake8
